name: material_wave_slider
description: Material Design 3 / Material You style wave slider.
version: 0.0.1
homepage: https://github.com/alexmercerind/material_wave_slider.git

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
